### ISSUE TITLE
YouTube package - JSON to CSV

### ISSUE THREAD

**Issue by bkok300** [isom-ds/apism#1]
Create a new function to convert the JSON format to CSV

- [x] AC1: Conversion of JSON to CSV
- [ ] <s>AC2: Flexible column selection</s>
- [ ] AC3: Tests passed @Dorian-Wang-Yilong 
- [x] AC4: Package updated

**Comment by bkok300** [comment]
Fixed incorrect search results mapping in original code - potential impact on video title and description!
![Image](https://github.com/user-attachments/assets/01be272c-7dc1-474d-b12c-af02baab3257)

AC2 not necessary - too complex to address within function... column selection can be done post export

**Comment by bkok300** [comment]
@Dorian-Wang-Yilong can you please test the following?

- [x] `Key` and `search.id.videoId` match
- [x] `yt.save_as_json` with the output of `search_videos_comments`, a random output, and the `flatten` parameter
- [x] `yt.save_as_csv` with the output of `search_videos_comments`, a random output, and the `shorten_keys` parameter

Upload screenshots of errors here
Thanks heaps! :)

**Comment by Dorian-Wang-Yilong** [comment]
Hey Brice, no problem! I just tested (using the code in the 'YouTube Data API v3 Examples' file) and seems all good:).

![image](https://github.com/user-attachments/assets/2b4842bc-2ae0-48ad-82df-0f4f2a3b20ae)
![image](https://github.com/user-attachments/assets/84476786-4310-4e51-b712-fc1b1a96902f)
![image](https://github.com/user-attachments/assets/234172f8-5f4f-473c-bfda-f1f9bf8e9f34)
![image](https://github.com/user-attachments/assets/d69c1f37-e5a0-4ff7-a981-0225f25b64b7)

**Comment by bkok300** [comment]
Thanks @Dorian-Wang-Yilong :)
What happens if you put a random file in the save functions?
e.g.
```python
incorrect_input = {
    'a': [1, 2, 3, 4],
    'b': {
        'c': [1, 2, 3, 4]
    }
}

yt.save_as_json(incorrect_input)
yt.save_as_csv(incorrect_input)
```

**Comment by bkok300** [comment]
Also, I figured out why this warning shows up... I need to do something like `await session.close()` at the end of the functions.
Will get that fixed soon... not a critical warning tho :)
![Image](https://github.com/user-attachments/assets/1db9d268-c6b4-463e-a156-c36acec7f836)

**Comment by Dorian-Wang-Yilong** [comment]
> Thanks @Dorian-Wang-Yilong :) What happens if you put a random file in the save functions? e.g.
> 
> ```python
> incorrect_input = {
>     'a': [1, 2, 3, 4],
>     'b': {
>         'c': [1, 2, 3, 4]
>     }
> }
> 
> yt.save_as_json(incorrect_input)
> yt.save_as_csv(incorrect_input)
> ```

it shows like this: 
![image](https://github.com/user-attachments/assets/03579c39-a64b-480e-a5f5-668a2f0e3c13)
![image](https://github.com/user-attachments/assets/27fb47df-c559-42d7-a669-c141488dbd60)

**Comment by briceshun** [comment]
I guess it's ok - we can infer that it's not the right format from the error message 😃 

Thanks heaps for testing @Dorian-Wang-Yilong !

I see you're a night owl too ;)

**Comment by Dorian-Wang-Yilong** [comment]
awesome, no problem at all, hhhhhh have a good night ;)

**Comment by bkok300** [comment]
New bugs found... @Dorian-Wang-Yilong 
Working on fixes:
- [x] `\r\n` line breaks messing up CSV structure
- [x] No results returned

![Image](https://github.com/user-attachments/assets/7a4e46ef-6680-421f-87a0-35757a29b210)

![Image](https://github.com/user-attachments/assets/65167cfc-0c52-4aee-90ca-26e847f7c2b8)

**Comment by bkok300** [comment]
@Dorian-Wang-Yilong 
Updated the package - line breaks and no results fixed for CSV output. Session closed error fixed too
Here is some code that you can use to collect daily data
```python
import uoa_isom_ds_sm_api_sdk.youtube as yt
import datetime
from dateutil.relativedelta import relativedelta
from tqdm import tqdm

# Set query and parameters
video_params = {
    'key': key,
    'part': 'id,statistics,topicDetails'
}
comments_params = {
    'key': key,
    'part': 'id,replies,snippet',
    'order': 'time'
}

async def collect_data(query, yyyy, mm, dd):
    # Define the start and end dates
    start_date = datetime.date(yyyy, mm, dd)
    end_date = datetime.date.today()

    # Calculate the total number of days for the progress bar
    total_days = (end_date - start_date).days

    # Initialize tqdm progress bar
    with tqdm(total=total_days, desc=f"Processing {start_date}") as pbar:
        # Loop through the dates
        current_date = start_date

        while current_date <= end_date:
            # Format the date as strings for 'publishedAfter' and 'publishedBefore'
            published_after = current_date.strftime('%Y-%m-%d') + 'T00:00:00Z'
            published_before = current_date.strftime('%Y-%m-%d') + 'T23:59:59Z'

            # Update the search parameters with the current date
            search_params = {
                'part': 'snippet',
                'type': 'video',
                'maxResults': 50,
                'relevanceLanguage': 'en',
                'publishedAfter': published_after,
                'publishedBefore': published_before,
                'order': 'viewCount'
            }
            
            custom_params = {
                'search': search_params,
                'videos': video_params,
                'commentThreads': comments_params
            }

            # Search API -> Videos API -> CommentThreads API
            yt = YouTubeAPI(api_key=key, params=custom_params)
            await yt.search(query)
            await yt.videos()
            await yt.comment_threads()
            await yt.transcripts()

            # Process or store the results as needed
            yt.to_csv(default_cols=True, shorten_cols=True, force_output=True)

            # Move to the next day
            current_date += datetime.timedelta(days=1)

            # Update progress bar description with the current date
            pbar.set_description(f"Processing {current_date.strftime('%Y-%m-%d')}")

            # Update the progress bar
            pbar.update(1)

# Example call
await collect_data('FTX crypto', 2024, 10, 1)
```

**Comment by Dorian-Wang-Yilong** [comment]
Hey Brice, seems like hmmm there is a package called tqdm that cannot be found. Here's the error message 😺:



ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], [line 4](vscode-notebook-cell:?execution_count=1&line=4)
      [2](vscode-notebook-cell:?execution_count=1&line=2) import datetime
      [3](vscode-notebook-cell:?execution_count=1&line=3) from dateutil.relativedelta import relativedelta
----> [4](vscode-notebook-cell:?execution_count=1&line=4) from tqdm import tqdm
      [6](vscode-notebook-cell:?execution_count=1&line=6) # Set query and parameters
      [7](vscode-notebook-cell:?execution_count=1&line=7) video_params = {
      [8](vscode-notebook-cell:?execution_count=1&line=8)     'key': key,
      [9](vscode-notebook-cell:?execution_count=1&line=9)     'part': 'id,statistics,topicDetails'
     [10](vscode-notebook-cell:?execution_count=1&line=10) }

ModuleNotFoundError: No module named 'tqdm'

![image](https://github.com/user-attachments/assets/5f27c532-c5a8-40b8-9cbe-0e88b056cb40)

**Comment by bkok300** [comment]
@Dorian-Wang-Yilong `pip install tqdm`

**Comment by Dorian-Wang-Yilong** [comment]
Hey Brice, I just tried the transcript one, and it seems like currently it can't find the video, just tried 4 videos and it doesn't work....
![image](https://github.com/user-attachments/assets/2deae5b6-b814-4acb-a694-42e8839becc3)

**Comment by bkok300** [comment]
@Dorian-Wang-Yilong 
Search doesn't search for the video ID, it searches for a keyword like you would in youtube
If you want to pass the video ID for transcripts you'll have to do
```python
await yt.transcripts(['yourvideoID'])
```
same for comments

Have a look at the example notebook
https://github.com/isom-ds/apism/blob/main/apism/youtube_example.ipynb

**Comment by Dorian-Wang-Yilong** [comment]
Hey Brice, good evening~ 

Hmmm currently it suddenly shows "failed to fetch data." 5 minutes ago, the same code worked without such issues, sorry I may need a bit help ;-;

![image](https://github.com/user-attachments/assets/b35e2440-682a-4d9d-9cd4-4ae62cbafece)

**Comment by Dorian-Wang-Yilong** [comment]
![image](https://github.com/user-attachments/assets/12944f95-606e-4dbc-a047-22b04c11009d)

I feel it’s not related to the code. Some code that was working before is now showing similar issues.....

**Comment by bkok300** [comment]
@Dorian-Wang-Yilong 
download this notebook and give it a try
https://github.com/isom-ds/apism/blob/main/apism/youtube_example.ipynb

if you're still having issues we can chat after our catch up with johnny

**Comment by Dorian-Wang-Yilong** [comment]
It stopped at the second code cell, and the problem is the same... maybe I’ll catch up with you tomorrow. Thanks Brice, you rest well! :)
![image](https://github.com/user-attachments/assets/e53b14a4-dd35-4b7a-b573-8f0596db8dc0)
